name: ${APP_NAME:-assessment-platform}

services:
  # MongoDB Service
  mongodb:
    image: mongo:latest
    container_name: ${APP_NAME:-assessment-platform}-mongodb
    restart: always
    volumes:
      - mongodb-data:/data/db
    networks:
      - assessment-platform-network
    # No ports exposed to host in production for security
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G

  # Bun.js Server Service
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: ${REGISTRY_REPO:-srajasimman}/${APP_NAME:-assessment-platform}-server:${SERVER_VERSION:-latest}
    container_name: ${APP_NAME:-assessment-platform}-server
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://${APP_NAME:-assessment-platform}-mongodb:27017/${APP_NAME:-assessment-platform}
    depends_on:
      - mongodb
    networks:
      - assessment-platform-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M

  # React Client Service with Nginx
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: ${REGISTRY_REPO:-srajasimman}/${APP_NAME:-assessment-platform}-client:${CLIENT_VERSION:-latest}
    container_name: ${APP_NAME:-assessment-platform}-client
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - server
    networks:
      - ${APP_NAME:-assessment-platform}-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M

networks:
  assessment-platform-network:
    driver: bridge

volumes:
  mongodb-data:
    driver: local
