name: assessment-platform-dev

services:
  # MongoDB Service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - assessment-network

  # Node.js Server Service
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: assessment-server
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/assessment-platform
      - NODE_ENV=development
    depends_on:
      - mongodb
    networks:
      - assessment-network

  # React Client Service
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: assessment-client
    restart: always
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    depends_on:
      - server
    networks:
      - assessment-network

networks:
  assessment-network:
    driver: bridge

volumes:
  mongodb-data:
