name: assessment-platform

services:
  # MongoDB Service
  mongodb:
    image: mongo:latest
    container_name: assessment-platform-mongodb
    restart: always
    volumes:
      - mongodb-data:/data/db
    networks:
      - assessment-platform-network
    # No ports exposed to host in production for security
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G

  # Node.js Server Service
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    image: srajasimman/assessment-platform-server:latest
    container_name: assessment-platform-server
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://assessment-platform-mongodb:27017/assessment-platform
    depends_on:
      - mongodb
    networks:
      - assessment-platform-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M

  # React Client Service with Nginx
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    image: srajasimman/assessment-platform-client:latest
    container_name: assessment-platform-client
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - server
    networks:
      - assessment-platform-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M

networks:
  assessment-platform-network:
    driver: bridge

volumes:
  mongodb-data:
    driver: local
