name: Build and Push Docker Images

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]
  # Allow manual trigger
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  APP_NAME: assessment-platform
  REGISTRY_REPO: docker.io/${{ github.repository_owner }}
  VERSION: ${{ github.event_name == 'push' && github.ref_type == 'tag' && github.ref_name || github.sha }}
  REACT_APP_API_URL: http://localhost:5000/api
  MONGODB_URI: mongodb://mongodb:27017/assessment-platform

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Container Registry
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/bake-action@v6
        with:
          push: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
