name: Pull Request Validation
run-name: Pull Request Validation for ${{ github.event.pull_request.title }}

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  validate-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Validate Commit Messages
        uses: srajasimman/conventional-commit-validator@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  time-to-review:
    runs-on: ubuntu-latest
    needs: validate-commits
    if: github.event.action == 'opened' || github.event.action == 'reopened'
    name: Calculate review time
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Calculate review time
        uses: srajasimman/time-to-review@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  assign-reviewers:
    runs-on: ubuntu-latest
    needs: time-to-review
    if: github.event.action == 'opened' || github.event.action == 'reopened'
    name: Assign reviewers
    steps:
      - name: Auto Assign Action
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: '.github/auto-assign.yml'
